### ISSUE TITLE
Add Support for sigil the doom 1 wad even sigil compat doesn't work and that is supposed to be vanilla compatiblele 

### ISSUE THREAD

**Issue by nbk935** [fgsfdsfgs/chocolate-doom#12]
### Background

Version of Chocolate Doom:

Operating System and version:

Game: (Doom/Heretic/Hexen/Strife/other)

Any loaded WADs and mods (please include full command line):

### Bug description

Observed behavior:

Expected behavior:

**Comment by koutsie** [comment]
This is a really odd issue, it doesn't seem to want to load for some reason.

+1 on the bug report.

**Comment by fgsfdsfgs** [comment]
I have synced the port with upstream and now SIGIL_COMPAT does load. Unfortunately merely looking in the wrong direction in E5M1 causes a visplane overflow, since even SIGIL_COMPAT requires a limit-removing port, which Chocolate Doom is not.
I can raise some of the static limits in this fork, but we will need a more permanent solution in the form of a Boom-compatible or limit-removing port.
